version: '3.8'

services:
  fastapi:
    build: ./fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - ./fastapi_app:/app
    restart: always

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=http://fastapi:8000
    volumes:
      - ./streamlit_app:/app
    restart: always